### ISSUE TITLE
Color Scheme

### ISSUE THREAD

**Issue by markusrubey** [where2help/creative#5]
There already is an issue related to our current color scheme at where2help/where2help#11

I would like to continue the discussion here under /creative. Currently our color scheme seems pretty dull and a little bit settings-screen-like. I think it could be much more lively and vibrant. As mentioned in where2help/where2help#11 readability is also an issue.

**Comment by klappradla** [comment]
Tool I came across: [coolors](https://coolors.co/)

**Comment by markusrubey** [comment]
This seems handy. I don't really have an eye for picking colors. To make things more lively i thought every category could have it's own color, so the app itself could stay more neutral toned.

**Comment by klappradla** [comment]
Just for the sake of completeness: [this](https://coolors.co/000000-002933-71d7cf-00ffff-f8f6e6) would be the auto-generated colorscheme using the (dark) logo:

![palette56507a8a61c75](https://cloud.githubusercontent.com/assets/3491815/11318823/c5ff9d8c-9061-11e5-9cac-a0dbf72faff9.png)
(I have an SVG and SASS version of it, too ✌️)

**Comment by klappradla** [comment]
Another light blue plus a fitting green tone would be in [this](https://coolors.co/app/000000-4b9697-71d7cf-aae7dc-55ffaa) scheme:
![palette_02](https://cloud.githubusercontent.com/assets/3491815/11318921/2cd7ac26-9066-11e5-8c4c-299f43a52a7c.png)

Green might be useful for some confirmation stuff etc.
