### ISSUE TITLE
App Main Menu

### ISSUE THREAD

**Issue by road2nowhere** [where2help/creative#7]
@markusrubey I actually quite liked your previous top menu proposal. 
- I would just make "my booked events" more visible. An icon with an indication how many events booked. Events will disappear if the time has passed
- I think it's ok to have profile & settings under the vertical dot icon, since they won't be used very frequently. 
- I also liked the filter in the top bar. I considered a floating button, too, but in the top bar it's nicely out of the way and maybe you won't need it too often once you have set it.

![w2h_app_list_061115](https://cloud.githubusercontent.com/assets/15609804/10998915/05211d12-8499-11e5-9899-5b7780ecda45.png)

I will wait with the subpages until we found a solution for the time slot booking.

The detail page looks pretty good to me, too. I think we only need to change it, if we need to do something about the time slots. And maybe we should link the name of the organization (i.e. we could ask for a link in the organization interface)

**Comment by markusrubey** [comment]
That bookmarking thingy with the numbering solves this nicely :+1: . I didn't like "My Bookings" in the overflow menu because it's more an action as an navigational step like "Settings". What would "Profile" be?

**Comment by road2nowhere** [comment]
Wasn't profile there previously? ;) I was expecting to find there my contact details. The data I've given on registration.

**Comment by markusrubey** [comment]
Profile was just empty and intended for displaying booked needs. I see. So i would take the profile header out of settings and build a editable profile page like the web-app has out of it?

**Comment by road2nowhere** [comment]
Yes, but only if that's a rather simple thing to do.... If I have a limited amount of change requests this wouldn't be the first thing I would choose ;)

**Comment by markusrubey** [comment]
Making it editable would require some effort. But should be possible. Always good to know what is still needed an how things will end up, because back and fourth is pretty time wasty.

Cool, so i would use that bookmarking icon as indicator as well instead of the checkmark to keep things consistent :smiley:

**Comment by markusrubey** [comment]
Just out of curiosity, what would those other change requests be? :smile:

**Comment by road2nowhere** [comment]
Haha! I'm waiting what comes out of the time slot discussion... I'm thinking also about putting the city selection in the filter, as you suggested previously, maybe with a distance filter (km around the city not around specific coordinates). Is that an option?

**Comment by road2nowhere** [comment]
My Bookings could actually just look like a filtered version of the main list. I added info about past bookings. It's not important but could be nice to know for the user. 
I think it's enough to have the cancel button on the detail page. What do you think?

![w2h_app_mybookings](https://cloud.githubusercontent.com/assets/15609804/11000070/ea892c18-849f-11e5-8dd8-a46103ba5885.png)

![w2h_app_mybookings_empty](https://cloud.githubusercontent.com/assets/15609804/11000077/efd5352c-849f-11e5-8beb-9b7a89fff24f.png)

**Comment by road2nowhere** [comment]
My spelling sucks

**Comment by markusrubey** [comment]
Sorry, was catching some sunshine :smiley: Well, not quite. In order to calculate the distance in km i would need the coordinates of the location and the coordinates of the user. I am really in favor of getting those coordinates into the needs as a requirement on creation/input. Searching for cities requires keyboard input, typing on mobile sucks, how do i know what city i can search for, ... sorting and filtering is the way to go in my opinion.

I like things simple, will only show the back option on the bookings page then. The info about past bookings on the bottom seems motivating, would have to check if I am able to get that information through the api though.

**Comment by road2nowhere** [comment]
Good choice :)
Maybe as a minimum version  we could just add a checkbox "Include nearby cities") like on skyscanner with the airports: http://www.skyscanner.at/

For me the user scenario looks like this:
- I'm a volunteer and I want to see where they need me in my city. --> As I understood this is possible even without detailed coordinates: If the NGO has typed in the city correctly, I can see all needs for the city. We will have info on where the user is (via the App).
- I might be available even to travel to other cities close by in order to help. --> In that case we can include cities in the range of X km from the currently set city, we don't need exact location data
- I might find it convenient to see where they need help closest to my current location, but it's not so important since I don't mind travelling to the other end of the city
- I might want to look where in other cities they need help but it's not very likely.

Could you maybe also describe the need from a user perspective, so I better understand what additional advantages the ccordinates might bring?

By the way, I would also prefer to have them so we can show a proper map and maybe link to the routeplanner, it just seems a bit of a challenge technically, if I understood correctly. I think we can't expect anyone to enter coordinates, but I would like to work the location definition like in eventbrite:

![image](https://cloud.githubusercontent.com/assets/15609804/11002122/3525e300-84ab-11e5-8838-af0bde603091.png)

![image](https://cloud.githubusercontent.com/assets/15609804/11002140/45f26b18-84ab-11e5-9798-ce864e7544da.png)

**Comment by markusrubey** [comment]
Filtering for predefined cities is possible as it is possible to filter on predefined categories like we do now. But as soon as you want to filter based on a distance, we would need a distance. A distance from supported cities to other cities could be predefined as well, but that is not a scaleable solution and results in the same problem which is: getting someone to define coordinates or in this case distances for a need/city. 

Let's pretend i have coordinates from every need. The app knows where the user is, the app knows where all the needs are located. As a user i could open the filter panel, switch to sort by distance, give it a radius in km and get all the needs around me.
